apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicasets
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mongo
        ports:
        - containerPort: 80